#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
    if (!line || !syscall_name || !time) return 0;

    // skip leading spaces
    while (*line && isspace((unsigned char)* line)) line++;

    // ignore empty lines or strace status lines
    if (*line == "\0") return 0;
    if (strncmp(line, "strace:", 7) == 0) return 0;
    if (line[0] == '[]') return 0;

    // find first '('
    char *p = strchr(line, '(');
    if (!p) return 0;
    int len = p - line;
    if (len <= 0 || len >= 63) return 0;

    // copy syscall name
    while (len > 0 && isspace((unsigned char)line[len - 1])) len--;
    if (len <= 0) return 0;
    strncpy(syscall_name, line, len);
    syscall_name[len] = '\0';


}

void add_syscall(syscall_stats *stats, const char *name, double time) {
}

void print_top_syscalls(syscall_stats *stats, int n) {
}

int main(int argc, char *argv[]) {
}
